# Generated by Django 5.0.7 on 2024-07-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='carmodel',
        ),
    ]
